### Create Activity
POST {{server}}/api/activity/create
Content-Type: application/json

{
  "description": "Fazer backend em Java"
}

### Create Activity
PATCH {{server}}/api/activity/update/2
Content-Type: application/json

{
  "description": "Fazer backend em TypeScript"
}

### Get All Activities
GET {{server}}/api/activity/get

### Delete Activity
DELETE {{server}}/api/activity/delete/2

