### Create Activity
POST {{server}}/api/activity/create
Content-Type: application/json

{
  "description": "Testando"
}

### Create Activity
PATCH {{server}}/api/activity/update/8
Content-Type: application/json

{
  "description": "Shaolin Matador de Porco"
}

### Get All Activities
GET {{server}}/api/activity/get

### Delete Activity
DELETE {{server}}/api/activity/delete/7

### Mark as completed
POST {{server}}/api/activity/complete/6

